# Generated by Django 4.2.15 on 2024-08-27 14:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("logic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="date_answered",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="logic.question"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="date_asked",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="question",
            name="keywords",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[("general", "General"), ("specific", "Specific")],
                max_length=20,
            ),
        ),
    ]
